// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecflowTutorial.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute(TestName="PegasusBdd")]
    [NUnit.Framework.DescriptionAttribute("PegasusBdd")]
    public partial class PegasusBddFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Senaryo1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("tr-TR"), "PegasusBdd", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestCaseAttribute(TestName="SenaryoPegasus")]
        [NUnit.Framework.DescriptionAttribute("SenaryoPegasus")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void SenaryoPegasus()
        {
            string[] tagsOfScenario = new string[] {
                    "mytag"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SenaryoPegasus", null, new string[] {
                        "mytag"});
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
  testRunner.And("\'//*[@id=\'fligth-searh\']/div[2]/div[1]/div/span/span[1]/span/span[2]\' objesine tı" +
                        "klanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 7
  testRunner.And("\'select2-search__field\' objesine \'istanbul-S.Gökçen\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 8
  testRunner.And("\'//*[@id=\'fligth-searh\']/div[2]/div[2]/div/span/span[1]/span/span[2]\' objesine tı" +
                        "klanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 9
  testRunner.And("\'select2-search__field\' objesine \'Samsun\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 10
  testRunner.And("\'//*[@id=\'fligth-searh\']/div[3]/div[1]/div/div[1]/span\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 11
  testRunner.And("\'Gidiş Bileti\' tarihi \'30.Mayıs.2020\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 12
  testRunner.And("\'5\' saniye süreyle beklenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 13
  testRunner.And("\'Dönüş Bileti\' tarihi \'6.Haziran.2020\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 14
  testRunner.And("\'5\' saniye süreyle beklenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 15
  testRunner.And("\'//*[@id=\"fligth-searh\"]/div[3]/div[3]/div/div[1]\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 16
  testRunner.And("\'//*[@id=\"fligth-searh\"]/div[3]/div[3]/div/div[2]/a\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 17
  testRunner.And("\'//*[@id=\"fligth-searh\"]/div[3]/div[4]/div/button\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 18
  testRunner.And("\'5\' saniye süreyle beklenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 19
  testRunner.And("\'//*[@id=\"boarding-card-body\"]/div[1]/div[3]/div[2]/div[2]/div[2]/div[1]/button/d" +
                        "iv/div[1]/div[1]/div[3]/div[3]\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 20
  testRunner.And("\'//*[@id=\"boarding-card-body\"]/div[1]/div[3]/div[2]/div[2]/div[2]/div[1]/div/div[" +
                        "2]/div[1]/button/div[2]/div/div/div\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 21
  testRunner.And("\'//*[@id=\"boarding-card-body\"]/div[1]/div[3]/div[3]/div[2]/div[2]/div[2]/button/d" +
                        "iv/div[1]/div[1]/div[3]/div[2]/div[1]\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 22
  testRunner.And("\'//*[@id=\"boarding-card-body\"]/div[1]/div[3]/div[3]/div[2]/div[2]/div[2]/div/div[" +
                        "2]/div[1]/button/div[2]/div/div/div\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 23
  testRunner.And("\'//*[@id=\"boarding-card-body\"]/div[1]/div[6]/div[2]/button[2]/div\' objesine tıkla" +
                        "nır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 24
  testRunner.And("\'10\' saniye süreyle beklenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 25
  testRunner.And("\'/html/body/div[17]/div/div[1]/div/div/div/div/div[3]/div[4]/button[2]\' objesine " +
                        "tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 26
  testRunner.And("\'3\' saniye süreyle beklenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 27
  testRunner.And("\'/html/body/div[17]/div/div[1]/div/div/div/div/div[3]/div[4]/button[2]\' objesine " +
                        "tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 28
  testRunner.And("\'3\' saniye süreyle beklenir.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 29
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[1]/div/div/input\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 30
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[1]/div/div/input\' objesine \'Cagatay\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 31
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[2]/div/div/label\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 32
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[2]/div/div/label\' objesine \'Sahin\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 33
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[3]/div[2]/div[1]/div[1]/div/div/label\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 34
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[3]/div[2]/div[1]/div[1]/div/div/label\' objesine \'27\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 35
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[3]/div[2]/div[1]/div[2]/div/div/label\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 36
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[3]/div[2]/div[1]/div[2]/div/div/label\' objesine \'07\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 37
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[3]/div[2]/div[1]/div[3]/div/div/label\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 38
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[3]/div[2]/div[1]/div[3]/div/div/label\' objesine \'1992\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 39
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[4]/div[2]/div/div[2]\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 40
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[5]/div[1]/div/div[3]/div[1]/div/div[2]/hr[2]\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 41
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[5]/div[1]/div/div[3]/div[1]/div/div[2]/hr[2]\' objesine \'\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 42
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[5]/div[1]/div/div[3]/div[2]/div/div[1]\' objesine \'\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 43
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[6]/div/div[2]/div/div/label\' objesine tıklanır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 44
  testRunner.And("\'/html/body/div[2]/div/div[4]/div[2]/div/div[3]/div[2]/div[1]/div/div/form/div/di" +
                        "v/div/div[6]/div/div[2]/div/div/label\' objesine \'\' yazılır.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
#line 45
  testRunner.And("\'//*[@id=\"boarding-card-body\"]/div/div[3]/div[2]/div[4]/button/div\' objesine tıkl" +
                        "anır..", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
